spring:
  profiles.active: cloud
server:
  port: ${PORT:9000}
security:
  basic:
    enabled: false
  user:
    name: admin
    password: pivotal
    roles: USER, ADMIN

welcome:
  msg: 'welcome to my world@!'

management:
  security:
    roles: ACTUATOR

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
